config/routes.rb
Rails.application.routes.draw do
  resources :utentis
  resources :horses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/index', to: 'home#index', as: 'index'

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/horse.rb
class Horse < ApplicationRecord
    has_one_attached :cover
end

app/models/utenti.rb
class Utenti < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index 
    end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: %i[ show edit update destroy ]

  # GET /horses or /horses.json
  def index
    @horses = Horse.all
  end

  # GET /horses/1 or /horses/1.json
  def show
  end

  # GET /horses/new
  def new
    @horse = Horse.new
  end

  # GET /horses/1/edit
  def edit
  end

  # POST /horses or /horses.json
  def create
    @horse = Horse.new(horse_params)

    respond_to do |format|
      if @horse.save
        format.html { redirect_to @horse, notice: "CAVALLO CREATO" }
        format.json { render :show, status: :created, location: @horse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horses/1 or /horses/1.json
  def update
    respond_to do |format|
      if @horse.update(horse_params)
        format.html { redirect_to @horse, notice: "CAVALLO AGGIORNATO" }
        format.json { render :show, status: :ok, location: @horse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horses/1 or /horses/1.json
  def destroy
    @horse.destroy
    respond_to do |format|
      format.html { redirect_to horses_url, notice: "CAVALLO ELIMINATO" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horse
      @horse = Horse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def horse_params
      params.require(:horse).permit(:nome, :sesso, :descrizione, :età, :cover)
    end
end

app/controllers/utentis_controller.rb
class UtentisController < ApplicationController
  before_action :set_utenti, only: %i[ show edit update destroy ]

  # GET /utentis or /utentis.json
  def index
    @utentis = Utenti.all
  end

  # GET /utentis/1 or /utentis/1.json
  def show
  end

  # GET /utentis/new
  def new
    @utenti = Utenti.new
  end

  # GET /utentis/1/edit
  def edit
  end

  # POST /utentis or /utentis.json
  def create
    @utenti = Utenti.new(utenti_params)

    respond_to do |format|
      if @utenti.save
        format.html { redirect_to @utenti, notice: "UTENTE CREATI" }
        format.json { render :show, status: :created, location: @utenti }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @utenti.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utentis/1 or /utentis/1.json
  def update
    respond_to do |format|
      if @utenti.update(utenti_params)
        format.html { redirect_to @utenti, notice: "UTENTE AGGIORNATO" }
        format.json { render :show, status: :ok, location: @utenti }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @utenti.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utentis/1 or /utentis/1.json
  def destroy
    @utenti.destroy
    respond_to do |format|
      format.html { redirect_to utentis_url, notice: "UTENTE ELIMINATO" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utenti
      @utenti = Utenti.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def utenti_params
      params.require(:utenti).permit(:cognome, :nome, :email, :numero, :annotazioni)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/utentis_helper.rb
module UtentisHelper
end

app/views/home/index.html.erb
<br>



<div class="container-fluid">
<div class="card-deck">
  <div class="card">
    <%= image_tag 'a1.jpg', class:"card-img-top" %>
    <div class="card-body">
      <h5 class="card-title text">CAVALLO NORDICO</h5>
      <p class="card-text text">Il suo corpo dalle forme armoniche ed eleganti è ricoperto di un pelame corto e liscio,
       che è variamente colorato, la sua testa è molto allungata, gli occhi sono grandi ed espressivi, le orecchie piccole,
        mobili e diritte. Il collo che è lungo e compresso è ornato da una criniera formata da crini lunghi e spioventi.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <%= image_tag 'a2.jpg', class:"card-img-top" %>
    <div class="card-body">
      <h5 class="card-title text">CAVALLO SUDDITO</h5>
      <p class="card-text text">Il suo corpo dalle forme armoniche ed eleganti è ricoperto di un pelame corto e liscio,
      che è variamente colorato, la sua testa è molto allungata, gli occhi sono grandi ed espressivi, le orecchie piccole,
       mobili e diritte. Il collo che è lungo e compresso è ornato da una criniera formata da crini lunghi e spioventi.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <%= image_tag 'a3.jpg', class:"card-img-top" %>
    <div class="card-body">
      <h5 class="card-title text">CAVALLO MAGNIFICO</h5>
      <p class="card-text text">Il suo corpo dalle forme armoniche ed eleganti è ricoperto di un pelame corto e liscio,
      che è variamente colorato, la sua testa è molto allungata, gli occhi sono grandi ed espressivi, le orecchie piccole,
       mobili e diritte. Il collo che è lungo e compresso è ornato da una criniera formata da crini lunghi e spioventi.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>
</div>



<br>

app/views/horses/_form.html.erb
<%= form_with(model: horse) do |form| %>
  <% if horse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
        <% horse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">


  <div class="field">
    <h5><%= form.label :immagine, class:"d-flex justify-content-center" %></h5>
    <%= form.file_field :cover, class:"form-control" %>
  </div>

  <br>

  <div class="field">
    <h5><%= form.label :nome, class:"d-flex justify-content-center" %></h5>
    <%= form.text_field :nome, class:"form-control" %>
  </div>

  <br>

  <div class="field">
    <h5><%= form.label :sesso, class:"d-flex justify-content-center" %></h5>
    <%= form.text_field :sesso, class:"form-control" %>
  </div>

  <br>

  <div class="field">
    <h5><%= form.label :descrizione, class:"d-flex justify-content-center" %></h5>
    <%= form.text_area :descrizione, class:"form-control" %>
  </div>

  <br>

  <div class="field">
    <h5><%= form.label :età, class:"d-flex justify-content-center" %></h5>
    <%= form.number_field :età, class:"form-control" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit 'CREA CAVALLO', class:"btn btn-primary w-100" %>
  </div>
<% end %>


</div>

app/views/horses/edit.html.erb
<br>



<div class="d-flex justify-content-center">
<h1>MODIFICA CAVALLO</h1>
</div>



<br>



<%= render 'form', horse: @horse %>

<div class="container">

<div style="padding: 10px"></div>

<%= link_to 'MOSTRA', @horse, class:"btn btn-success w-100" %> 

<div style="padding: 10px"></div>

<%= link_to 'INDIETRO', horses_path, class:"btn btn-info w-100" %>

<div style="padding: 10px"></div>

</div>

app/views/horses/index.html.erb
<p id="notice"><%= notice %></p>




<br>



<div class="d-flex justify-content-center">
<h1>CAVALLI</h1>
</div>


<br>



<div class="container">

<div class="row row-cols-1 row-cols-md-2">

<% @horses.each do |horse| %>

  
    <div class="col mb-4">
      <div class="card">
        <% if horse.cover.attached? %>
          <%= image_tag url_for(horse.cover) %>
        <% end %> 
        <div class="card-body">

          
          <h5 class="text"><%= horse.nome %></h6> 



          <br>

          <h6 class="text"><%= horse.descrizione %></h6>

          <br>


          <div style="padding: 10px"></div>
          <%= link_to 'MOSTRA', horse, class:"btn btn-success w-100" %>
          <div style="padding: 10px"></div>
          <%= link_to 'MODIFICA', edit_horse_path(horse), class:"btn btn-primary w-100" %>
          <div style="padding: 10px"></div>
          <%= link_to 'ELIMINA', horse, method: :delete, data: { confirm: 'SEI SICURO?' }, class:"btn btn-danger w-100" %>
        </div>
      </div>
    </div>


<% end %>


</div>
</div>



<div class="container">

<%= link_to 'NUOVO CAVALLO', new_horse_path, class:"btn btn-primary w-100" %>

<div style="padding: 10px"></div>

</div>

app/views/horses/new.html.erb
<br>



<div class="d-flex justify-content-center">
<h1>NUOVO CAVALLO</h1>
</div>



<br>



<%= render 'form', horse: @horse %>



<br>



<div class="container">
<%= link_to 'INDIETRO', horses_path, class:"btn btn-info w-100" %>
</div>



<br>

app/views/horses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h5 class="text">IMMAGINE:</h5>
  <% if @horse.cover.attached? %>
    <div class="d-flex justify-content-center"><%= image_tag url_for(@horse.cover), class:"images" %></div>
  <% end %>
</p>

<div style="padding: 5px"></div>

<p>
  <h5 class="text">NOME:</h5>
  <p class="text"><%= @horse.nome %></p>
</p>

<div style="padding: 5px"></div>

<p>
  <h5 class="text">SESSO:</h5>
  <p class="text"><%= @horse.sesso %></p>
</p>

<div style="padding: 5px"></div>

<p>
  <h5 class="text">DESCRIZIONE:</h5>
  <div class="d-flex justify-content-center"><p class="questo text"><%= @horse.descrizione %></p></div>
</p>

<div style="padding: 5px"></div>

<p>
  <h5 class="text">ETÀ:</h5>
  <p class="text"><%= @horse.età %></p>
</p>


<div class="container">

<%= link_to 'MODIFICA', edit_horse_path(@horse), class:"btn btn-primary w-100" %> 

<div style="padding: 10px"></div>

<%= link_to 'INDIETRO', horses_path, class:"btn btn-info w-100" %>

<div style="padding: 10px"></div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="it">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Maneggio</title>

  </head>
  <body>



  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'HOME', index_path, class:"navbar-brand" %>
        <%= link_to 'CAVALLI', horses_path, class:"navbar-brand" %>
        <%= link_to 'NEWSLETTER', utentis_path, class:"navbar-brand" %>
      </li>
    </ul>
  </div>
</nav>



<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
<ol class="carousel-indicators">
  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
</ol>
<div class="carousel-inner">
  <div class="carousel-item active">
    <%= image_tag 'a1.jpg', class:"d-block w-100" %>
  </div>
  <div class="carousel-item">
    <%= image_tag 'a2.jpg', class:"d-block w-100" %>
  </div>
  <div class="carousel-item">
    <%= image_tag 'a3.jpg', class:"d-block w-100" %>
  </div>
</div>
<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="sr-only">Next</span>
</a>
</div>





<%= yield %>


<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example2" class="form-control" />
              <label class="form-label" for="form5Example2">Email address</label>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->

    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
        eum harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->





    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/utentis/_form.html.erb
<%= form_with(model: utenti) do |form| %>
  <% if utenti.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(utenti.errors.count, "error") %> prohibited this utenti from being saved:</h2>

      <ul>
        <% utenti.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container">


  <div class="field">
    <h5><%= form.label :cognome, class:"d-flex justify-content-center" %></h5>
    <%= form.text_field :cognome, class:"form-control" %>
  </div>

  <br>

  <div class="field">
    <h5><%= form.label :nome, class:"d-flex justify-content-center" %></h5>
    <%= form.text_field :nome, class:"form-control" %>
  </div>

  <br>

  <div class="field">
    <h5><%= form.label :email, class:"d-flex justify-content-center" %></h5>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <br>

  <div class="field">
    <h5><%= form.label :numero, class:"d-flex justify-content-center" %></h5>
    <%= form.number_field :numero, class:"form-control" %>
  </div>

  <br>

  <div class="field">
    <h5><%= form.label :annotazioni, class:"d-flex justify-content-center" %></h5>
    <%= form.text_area :annotazioni, class:"form-control" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit 'CREA UTENTE', class:"btn btn-primary w-100" %>
  </div>
<% end %>

app/views/utentis/edit.html.erb
<br>



<div class="d-flex justify-content-center">
<h1>MODIFICA UTENTI</h1>
</div>


<br>



<div class="container">

<%= render 'form', utenti: @utenti %>

<div style="padding: 10px"></div>

<%= link_to 'MOSTRA', @utenti, class:"btn btn-success w-100" %> 

<div style="padding: 10px"></div>

<%= link_to 'INDIETRO', utentis_path, class:"btn btn-info w-100" %>

<div style="padding: 10px"></div>

</div>

app/views/utentis/index.html.erb
<p id="notice"><%= notice %></p>



<br>



<div class="d-flex justify-content-center">
<h1>UTENTI</h1>
</div>



<br>



<table class="table">
  <thead>
    <tr>
      <th class="text">COGNOME</th>
      <th class="text">NOME</th>
      <th class="text">EMAIL</th>
      <th class="text">NUMERO</th>
      <th class="text">ANNOTAZIONI</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utentis.each do |utenti| %>
      <tr>
        <td class="text"><%= utenti.cognome %></td>
        <td class="text"><%= utenti.nome %></td>
        <td class="text"><%= utenti.email %></td>
        <td class="text"><%= utenti.numero %></td>
        <td class="text"><%= utenti.annotazioni %></td>
        <td><%= link_to 'MOSTRA', utenti, class:"btn btn-success w-100" %></td>
        <td><%= link_to 'MODIFICA', edit_utenti_path(utenti), class:"btn btn-primary w-100" %></td>
        <td><%= link_to 'ELIMINA', utenti, method: :delete, data: { confirm: 'SEI SICURO?' }, class:"btn btn-danger w-100" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<div class="container">

<%= link_to 'NUOVI UTENTI', new_utenti_path, class:"btn btn-primary w-100" %>

<div style="padding: 10px"></div>

</div>

app/views/utentis/new.html.erb
<br>



<div class="d-flex justify-content-center">
<h1>NUOVO UTENTE</h1>
</div>



<br>



<%= render 'form', utenti: @utenti %>



<br>



<div class="container">
<%= link_to 'INDIETRO', utentis_path, class:"btn btn-info w-100" %>
</div>



<br>

app/views/utentis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>COGNOME:</strong>
  <%= @utenti.cognome %>
</p>

<p>
  <strong>NOME:</strong>
  <%= @utenti.nome %>
</p>

<p>
  <strong>EMAIL:</strong>
  <%= @utenti.email %>
</p>

<p>
  <strong>NUMERO:</strong>
  <%= @utenti.numero %>
</p>

<p>
  <strong>ANNOTAZIONI:</strong>
  <%= @utenti.annotazioni %>
</p>


<div class="container">

<%= link_to 'MODIFICA', edit_utenti_path(@utenti), class:"btn btn-primary w-100" %> 

<div style="padding: 10px"></div>

<%= link_to 'INDIETRO', utentis_path, class:"btn btn-info w-100" %>

<div style="padding: 10px"></div>

</div>